project:
  type: website

website:
  title: "Analytics for Non-Profits"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - styles/styles.scss
      - cosmo
    toc: true
    mainfont: Nunito Sans
    date-format: long


execute:
  freeze: true
